# Generated by Django 4.2.7 on 2023-11-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='218 СМ × 95 СМ × 90 СМ', max_length=100, verbose_name='Размер'),
        ),
    ]
