# Generated by Django 4.2.7 on 2023-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='Нет фото', upload_to='categories/', verbose_name='Изображение категорий'),
        ),
    ]
