# Generated by Django 4.2.7 on 2023-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default='100 CM', max_length=100, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(default='100 CM', max_length=100, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(default='100 CM', max_length=100, verbose_name='Ширина'),
        ),
    ]
