# Generated by Django 4.2.7 on 2023-11-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_height_product_length_product_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
